#baseURL = "https://tinpanvalley.de"
title = "Tin Pan Valley"
languageCode = "de-DE"
theme = "hugoscroll" 

[Params]
  description = "About a Band"
  cover = "/tanpanvalley.jpg"

[context.production.environment]
  HUGO_VERSION = "0.36"