#aseURL = "https://hungry-bardeen-350de1.netlify.com/"
title = "Tin Pan Valley"
languageCode = "de-DE"
theme = "hugoscroll" 

[Params]
  description = "About a Band"
  cover = "/tanpanvalley.jpg"

[context.production.environment]
  HUGO_VERSION = "0.36"